export { postConfirmation } from "./auth/postConfirmation/resource"
export { getProfile } from "./auth/get-profile/resource"
export { addInventory } from "./inventory/add-inventory/resource"
export { deleteInventory } from "./inventory/delete-inventory/resource"
export { getInventory } from "./inventory/get-inventory/resource"
export { onUpload } from "./storage/on-upload/resource"
export { onDelete } from "./storage/on-delete/resource"
export { uploadFile } from "./storage/uploadFile/resource"
